#ddev-generated
services:
  wordmove:
    container_name: ddev-${DDEV_SITENAME}-wordmove
    build:
      context: ./wordmove-build
      args:
        DDEV_PHP_VERSION: ${DDEV_PHP_VERSION}
        username: ${USER}
        uid: ${DDEV_UID}
        gid: ${DDEV_GID}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

    user: "${DDEV_UID}:${DDEV_GID}"
    tty: true
    depends_on:
      - web
    command: sleep infinity
    restart: unless-stopped
    networks: ["default", "ddev_default"]
    working_dir: "/var/www/html/"
    volumes:
      - type: bind
        source: ../
        target: /var/www/html
        consistency: cached
      - .:/mnt/ddev_config:ro
      - ddev-global-cache:/mnt/ddev-global-cache
      - ddev-ssh-agent_socket_dir:/home/.ssh-agent
    hostname: ${DDEV_SITENAME}-wordmove
    environment:
      # copied from ddev web
      - COLUMNS
      - DOCROOT=${DDEV_DOCROOT}
      - DDEV_UID
      - DDEV_GID
      - DDEV_COMPOSER_ROOT
      - DDEV_DATABASE
      - DDEV_DOCROOT
      - DDEV_DATABASE_FAMILY
      - DDEV_HOSTNAME
      - DDEV_MUTAGEN_ENABLED
      - DDEV_PHP_VERSION
      - DDEV_PRIMARY_URL
      - DDEV_PROJECT
      - DDEV_PROJECT_TYPE
      - DDEV_ROUTER_HTTP_PORT
      - DDEV_ROUTER_HTTPS_PORT
      - DDEV_SITENAME
      - DDEV_TLD
      - DDEV_FILES_DIR
      - DDEV_FILES_DIRS
      - DDEV_WEB_ENTRYPOINT=/mnt/ddev_config/web-entrypoint.d
      - DDEV_WEBSERVER_TYPE
      - DDEV_XDEBUG_ENABLED
      - DDEV_VERSION
      - DEPLOY_NAME=local
      # - DRUSH_OPTIONS_URI=$DDEV_PRIMARY_URL
      # - DRUSH_ALLOW_XDEBUG=1
      - DOCKER_IP=127.0.0.1
      # - GOARCH
      # - GOOS
      - HOST_DOCKER_INTERNAL_IP=
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      # To expose a container port to a different host port, define the port as hostPort:containerPort
      # - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILPIT_PORT}:8025
      # You can optionally expose an HTTPS port option for any ports defined in HTTP_EXPOSE.
      # To expose an HTTPS port, define the port as securePort:containerPort.
      # - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILPIT_HTTPS_PORT}:8025
      - IS_DDEV_PROJECT=true
      # - LINES
      # - MYSQL_HISTFILE=/mnt/ddev-global-cache/mysqlhistory/${DDEV_SITENAME}-web/mysql_history
      # - MYSQL_PWD=db
      # - NODE_EXTRA_CA_CERTS=/mnt/ddev-global-cache/mkcert/rootCA.pem
      # - npm_config_cache=/mnt/ddev-global-cache/npm
      # - PGDATABASE=db
      # - PGHOST=db
      # - PGPASSWORD=db
      # - PGUSER=db
      # - PHP_IDE_CONFIG=serverName=${DDEV_SITENAME}.${DDEV_TLD}
      - SSH_AUTH_SOCK=/home/.ssh-agent/socket
      - TZ=
      - VIRTUAL_HOST=${DDEV_HOSTNAME}
